// A readable description of one OPC UA model of the document, as a single HTML
// file: its ObjectTypes and VariableTypes with their supertype, their
// instance declarations (with ModellingRule, type and the reference that holds
// them) and a diagram in the notation of OPC 10000-3; its DataTypes with
// their fields or values; its ReferenceTypes. Built from the Annex A libraries
// the model was imported into, with the diagrams the plugin and uaaml draw.
// The file needs nothing else: styles and pictures are inside.

using System.Globalization;
using System.Net;
using System.Text;
using Aml.Engine.CAEX;
using Aml.Engine.CAEX.Extensions;
using OpcUaAml.Diagram;
using OpcUaAml.Import;
using OpcUaAml.Types;

namespace OpcUaAml.Documentation;

public sealed class DocumentationOptions
{
    /// <summary>Levels of declarations each type's diagram shows.</summary>
    public int DiagramDepth { get; init; } = 2;

    /// <summary>Nodes a diagram shows at most; bigger types are cut, as the diagram says.</summary>
    public int DiagramNodes { get; init; } = 60;
}

public static class ModelDocumentation
{
    /// <summary>The documentation of the model <paramref name="namespaceUri"/> of the document.</summary>
    /// <exception cref="ArgumentException">The document holds no libraries of that model.</exception>
    public static string Html(CAEXDocument doc, string namespaceUri, DocumentationOptions? options = null)
    {
        options ??= new DocumentationOptions();
        var entry = NamespaceOverview.Of(doc).FirstOrDefault(e => e.NamespaceUri == namespaceUri)
                    ?? throw new ArgumentException($"The document holds no libraries of '{namespaceUri}'.", nameof(namespaceUri));
        var libraries = entry.Libraries.ToHashSet(StringComparer.Ordinal);

        var types = doc.CAEXFile.SystemUnitClassLib.Where(l => libraries.Contains(l.Name))
            .SelectMany(l => l.SystemUnitClass.SelectMany(c => c.Descendants<SystemUnitFamilyType>().Prepend(c)))
            .OrderBy(t => t.Name, StringComparer.OrdinalIgnoreCase).ToList();
        var variableTypes = types.Where(t => UaTypes.Chain(t).Any(c => c.Name == "BaseVariableType")).ToList();
        var objectTypes = types.Except(variableTypes).ToList();
        var dataTypes = doc.CAEXFile.AttributeTypeLib.Where(l => libraries.Contains(l.Name))
            .SelectMany(l => l.AttributeType).Where(a => !a.Name.StartsWith("ListOf", StringComparison.Ordinal))
            .OrderBy(a => a.Name, StringComparer.OrdinalIgnoreCase).ToList();
        var referenceTypes = doc.CAEXFile.InterfaceClassLib.Where(l => libraries.Contains(l.Name))
            .SelectMany(l => l.InterfaceClass).OrderBy(c => c.Name, StringComparer.OrdinalIgnoreCase).ToList();
        var anchors = types.ToDictionary(t => t.CAEXPath(), t => Anchor("type", t.Name), StringComparer.Ordinal);

        var html = new StringBuilder();
        var title = ShortName(namespaceUri);
        html.Append("<!DOCTYPE html>\n<html lang=\"en\"><head><meta charset=\"utf-8\">")
            .Append($"<title>{E(title)}</title><style>{Css}</style></head><body>\n");
        html.Append($"<header><h1>{E(title)}</h1><p class=\"uri\">{E(namespaceUri)}</p><p class=\"meta\">")
            .Append(entry.ModelVersion != null ? $"Version {E(entry.ModelVersion)}" : "")
            .Append(entry.PublicationDate is { } date ? $" · published {date:yyyy-MM-dd}" : "")
            .Append($" · {objectTypes.Count} ObjectTypes, {variableTypes.Count} VariableTypes, {dataTypes.Count} DataTypes, {referenceTypes.Count} ReferenceTypes")
            .Append("</p></header>\n");

        // Contents
        html.Append("<nav><h2>Contents</h2>");
        Toc(html, "ObjectTypes", objectTypes.Select(t => (t.Name, anchors[t.CAEXPath()])));
        Toc(html, "VariableTypes", variableTypes.Select(t => (t.Name, anchors[t.CAEXPath()])));
        Toc(html, "DataTypes", dataTypes.Select(d => (d.Name, Anchor("data", d.Name))));
        Toc(html, "ReferenceTypes", referenceTypes.Select(r => (r.Name, Anchor("ref", r.Name))));
        html.Append("</nav>\n<main>\n");

        Types(html, "ObjectTypes", objectTypes, anchors, options);
        Types(html, "VariableTypes", variableTypes, anchors, options);

        if (dataTypes.Count > 0)
        {
            html.Append("<h2>DataTypes</h2>\n");
            foreach (var d in dataTypes) DataType(html, d);
        }
        if (referenceTypes.Count > 0)
        {
            html.Append("<h2>ReferenceTypes</h2>\n");
            foreach (var r in referenceTypes) ReferenceType(html, r);
        }

        html.Append("</main>\n<footer>Generated by AMLOpcUa from the document's OPC 10000-83 Annex A libraries. ")
            .Append("Diagrams in the notation of OPC 10000-3: rectangle Object, rounded rectangle Variable, ellipse Method, shaded types; ")
            .Append("M Mandatory, O Optional, MP and OP placeholders, E ExposesItsArray.</footer>\n</body></html>\n");
        return html.ToString();
    }

    private static void Toc(StringBuilder html, string heading, IEnumerable<(string Name, string Anchor)> items)
    {
        var list = items.ToList();
        if (list.Count == 0) return;
        html.Append($"<h3>{heading} ({list.Count})</h3><p class=\"toc\">")
            .Append(string.Join(" · ", list.Select(i => $"<a href=\"#{i.Anchor}\">{E(i.Name)}</a>")))
            .Append("</p>");
    }

    private static void Types(StringBuilder html, string heading, List<SystemUnitFamilyType> types, Dictionary<string, string> anchors,
        DocumentationOptions options)
    {
        if (types.Count == 0) return;
        html.Append($"<h2>{heading}</h2>\n");
        foreach (var type in types)
        {
            html.Append($"<section id=\"{anchors[type.CAEXPath()]}\"><h3>{E(type.Name)}")
                .Append(UaTypes.IsAbstract(type) ? " <span class=\"badge\">abstract</span>" : "").Append("</h3>");
            var super = UaTypes.Resolve(type.CAEXDocument, type.RefBaseClassPath);
            if (super != null)
                html.Append("<p class=\"meta\">Subtype of ")
                    .Append(anchors.TryGetValue(super.CAEXPath(), out var a) ? $"<a href=\"#{a}\">{E(super.Name)}</a>" : E(super.Name))
                    .Append("</p>");
            if (DescriptionOf(type) is { } text) html.Append($"<p>{E(text)}</p>");

            UaDiagram diagram;
            try { diagram = DiagramLayout.Apply(DiagramBuilder.Build(type, options.DiagramDepth, options.DiagramNodes)); }
            catch (Exception ex) when (ex is InvalidOperationException or ArgumentException)
            {
                html.Append($"<p class=\"meta\">No diagram: {E(ex.Message)}</p></section>\n");
                continue;
            }

            // The declarations: the diagram's first level, with the reference that holds each.
            var root = diagram.Nodes[0];
            var rows = diagram.Nodes.Where(n => n.Depth == 1).ToList();
            if (rows.Count > 0)
            {
                html.Append("<table><thead><tr><th>Name</th><th>NodeClass</th><th>Type</th><th>Rule</th><th>Reference</th></tr></thead><tbody>");
                foreach (var n in rows)
                {
                    var reference = diagram.Edges.FirstOrDefault(e => e.From == root.Id && e.To == n.Id)?.ReferenceType ?? "";
                    html.Append($"<tr><td>{E(n.Name)}</td><td>{n.Kind}</td><td>{E(n.TypeName ?? "")}</td>")
                        .Append($"<td>{E(RuleName(n.ModellingRule))}</td><td>{E(reference)}</td></tr>");
                }
                html.Append("</tbody></table>");
            }
            html.Append("<details><summary>Diagram")
                .Append(diagram.Truncated ? $" (the first {diagram.Nodes.Count} nodes)" : "")
                .Append("</summary><div class=\"diagram\">")
                .Append(InlineSvg(SvgWriter.Write(diagram)))
                .Append("</div></details>");
            if (StateMachines.IsMachine(type)) Machine(html, StateMachines.Read(type));
            html.Append("</section>\n");
        }
    }

    /// <summary>
    /// A finite state machine of the type: its states and transitions as a
    /// table, and the machine as a state chart. What the modeler shows while
    /// the machine is built, in the documentation of the finished model.
    /// </summary>
    private static void Machine(StringBuilder html, StateMachine machine)
    {
        if (machine.IsEmpty) return;
        html.Append("<p class=\"meta\">State machine (OPC 10000-5 Annex B)</p>");

        if (machine.States.Count > 0)
        {
            html.Append("<table><thead><tr><th>State</th><th>Number</th></tr></thead><tbody>");
            foreach (var state in machine.States)
                html.Append($"<tr><td>{E(state.Name)}</td><td>{state.Number?.ToString(CultureInfo.InvariantCulture) ?? ""}</td></tr>");
            html.Append("</tbody></table>");
        }
        if (machine.Transitions.Count > 0)
        {
            html.Append("<table><thead><tr><th>Transition</th><th>Number</th><th>From</th><th>To</th><th>Caused by</th></tr></thead><tbody>");
            foreach (var transition in machine.Transitions)
            {
                html.Append($"<tr><td>{E(transition.Name)}</td><td>{transition.Number?.ToString(CultureInfo.InvariantCulture) ?? ""}</td>")
                    .Append($"<td>{E(machine.NameOf(transition.From))}</td><td>{E(machine.NameOf(transition.To))}</td>")
                    .Append($"<td>{E(transition.Cause is { Length: > 0 } cause ? cause + "()" : "")}</td></tr>");
            }
            html.Append("</tbody></table>");
        }
        if (StateChart.Svg(machine) is { Length: > 0 } chart)
            html.Append("<details open><summary>State chart</summary><div class=\"diagram\">").Append(InlineSvg(chart)).Append("</div></details>");
    }

    private static void DataType(StringBuilder html, AttributeTypeType d)
    {
        html.Append($"<section id=\"{Anchor("data", d.Name)}\"><h3>{E(d.Name)}</h3>");
        var super = LastSegment(d.RefAttributeType);
        if (super.Length > 0) html.Append($"<p class=\"meta\">Subtype of {E(super)}</p>");
        if (!string.IsNullOrWhiteSpace(d.Description)) html.Append($"<p>{E(d.Description)}</p>");

        var values = d.Constraint.SelectMany(c => c.NominalScaledType?.RequiredValue ?? Enumerable.Empty<string>()).ToList();
        if (values.Count > 0)
        {
            html.Append("<p class=\"meta\">Values</p><p>").Append(string.Join(" · ", values.Select(E))).Append("</p>");
        }
        var fields = d.Attribute.Where(a => a.Name != "Description").ToList();
        if (fields.Count > 0)
        {
            html.Append("<table><thead><tr><th>Field</th><th>DataType</th><th>Description</th></tr></thead><tbody>");
            foreach (var f in fields)
            {
                var type = LastSegment(f.RefAttributeType) is { Length: > 0 } t ? t : f.AttributeDataType ?? "";
                html.Append($"<tr><td>{E(f.Name)}</td><td>{E(type)}</td><td>{E(f.Description ?? "")}</td></tr>");
            }
            html.Append("</tbody></table>");
        }
        html.Append("</section>\n");
    }

    private static void ReferenceType(StringBuilder html, InterfaceFamilyType r)
    {
        html.Append($"<section id=\"{Anchor("ref", r.Name)}\"><h3>{E(r.Name)}</h3>");
        var super = LastSegment(r.RefBaseClassPath);
        var inverse = r.InterfaceClass.FirstOrDefault()?.Name;
        html.Append("<p class=\"meta\">")
            .Append(super.Length > 0 ? $"Subtype of {E(super)}" : "")
            .Append(inverse != null ? $"{(super.Length > 0 ? " · " : "")}inverse name {E(inverse)}" : "")
            .Append("</p>");
        if (!string.IsNullOrWhiteSpace(r.Description)) html.Append($"<p>{E(r.Description)}</p>");
        html.Append("</section>\n");
    }

    private static string? DescriptionOf(SystemUnitFamilyType type) =>
        !string.IsNullOrWhiteSpace(type.Description) ? type.Description
        : type.Attribute["Description"]?.Value is { Length: > 0 } text ? text : null;

    private static string RuleName(string? rule) => rule switch
    {
        "M" => "Mandatory",
        "O" => "Optional",
        "MP" => "MandatoryPlaceholder",
        "OP" => "OptionalPlaceholder",
        "E" => "ExposesItsArray",
        _ => rule ?? "",
    };

    private static string InlineSvg(string svg)
    {
        var start = svg.IndexOf("<svg", StringComparison.Ordinal);
        return start > 0 ? svg[start..] : svg;
    }

    private static string LastSegment(string? path)
    {
        if (string.IsNullOrEmpty(path)) return "";
        var last = path.TrimEnd(']').Split('/').Last();
        return last.Trim('[', ']');
    }

    private static string Anchor(string kind, string name) =>
        kind + "-" + new string(name.Select(c => char.IsLetterOrDigit(c) ? c : '-').ToArray());

    private static string ShortName(string uri)
    {
        var parts = uri.Split(new[] { '/', ':' }, StringSplitOptions.RemoveEmptyEntries);
        return parts.Length == 0 ? uri : parts[^1];
    }

    private static string E(string text) => WebUtility.HtmlEncode(text);

    private const string Css =
        "body{font-family:'Segoe UI',Arial,sans-serif;color:#1f2328;margin:0 auto;max-width:1100px;padding:24px;line-height:1.45}"
        + "h1{margin:0}h2{margin-top:40px;border-bottom:1px solid #d0d7de;padding-bottom:4px}h3{margin:28px 0 4px}"
        + ".uri{font-family:Consolas,monospace;color:#57606a;margin:2px 0}.meta{color:#57606a;margin:2px 0}"
        + ".badge{font-size:12px;font-weight:normal;border:1px solid #d0d7de;border-radius:9px;padding:0 7px;color:#57606a}"
        + "nav .toc{font-size:14px}table{border-collapse:collapse;margin:8px 0;font-size:14px;width:100%}"
        + "th,td{border:1px solid #d0d7de;padding:3px 8px;text-align:left;vertical-align:top}th{background:#f6f8fa}"
        + "details{margin:6px 0}summary{cursor:pointer;color:#0969da}.diagram{overflow:auto;border:1px solid #d0d7de;background:#fff;padding:6px}"
        + "footer{margin-top:40px;color:#57606a;font-size:13px;border-top:1px solid #d0d7de;padding-top:8px}";
}
