<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>uaaml</AssemblyName>
    <RootNamespace>OpcUaAml.Tool</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OpcUaAml.Core\OpcUaAml.Core.csproj" />
  </ItemGroup>
</Project>
